name: Update Daily Weather

on:
  schedule:
    - cron: "0 12 * * *" # runs daily at 12:00 UTC
  workflow_dispatch:

jobs:
  update-weather:
    name: update weather from this day
    runs-on: ubuntu-latest
    steps:
      - name: update weather from this day
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch weather (Open-Meteo, no API key needed)
        run: |
          # coords
          LAT="32.6"
          LON="-85.5"

          RESPONSE=$(curl -s "https://api.open-meteo.com/v1/forecast?latitude=$LAT&longitude=$LON&current_weather=true&hourly=relative_humidity_2m,precipitation_probability")

          TEMP=$(echo $RESPONSE | jq -r '.current_weather.temperature')
          HUM=$(echo $RESPONSE | jq -r '.hourly.relative_humidity_2m[0]')
          RAIN=$(echo $RESPONSE | jq -r '.hourly.precipitation_probability[0]')

          echo "Today's weather: rain chance=$RAIN, temp=$TEMP°C, humidity=$HUM"

          echo "{ \"temp\": \"$TEMP\", \"humidity\": \"$HUM\", \"rain\": \"$RAIN\" }" > static/weather.json
          
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add weather.json
          git commit -m "Update daily weather [skip ci]" || echo "No changes to commit"
          git push
